all: build

build: main.cpp figure02.h eq_triangle.h isos_triangle.h parallelogramm.h rectangle.h rhombus.h right_triangle.h square.h triangle.h 
	g++ -std=c++2b *.cpp -o main


clean:
	 rm -rf  *.out *.gch
