all: build

build: main.cpp figure03.h eq_triangle.h isos_triangle.h parallelogramm.h rectangle.h rhombus.h right_triangle.h square.h triangle.h 
	g++ -std=c++2b main.cpp eq_triangle.cpp isos_triangle.cpp parallelogramm.cpp rectangle.cpp rhombus.cpp right_triangle.cpp square.cpp triangle.cpp


clean:
	 rm -rf  *.out *.gch
