all: build

build: main.cpp figure02.h eq_triangle.h isos_triangle.h parallelogram.h rectangle.h rhombus.h right_triangle.h square.h triangle.h 
	g++ -std=c++2b main.cpp 


clean:
	 rm -rf  *.out *.gch
